name: Build for Android

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      version:
        description: 'App version (e.g. 0.1.7)'
        required: true
        default: '0.0.0'

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version != '' && github.event.inputs.version || github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Prepare Capacitor Android
        working-directory: ./capacitor
        run: |
          npm ci
          npm install @capacitor/android
          npx cap add android
          npx cap sync

      - name: Update Android Version
        run: |
          MAJOR=$(echo "${{ env.VERSION }}" | cut -d. -f1)
          sed -i 's/versionName ".*"/versionName "${{ env.VERSION }}"/' capacitor/android/app/build.gradle
          sed -i "s/versionCode [0-9]\+/versionCode $MAJOR/" capacitor/android/app/build.gradle

      - uses: android-actions/setup-android@v3

      - name: Build Android APK
        working-directory: ./capacitor/android
        run: ./gradlew assembleDebug

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lost-mine-android-${{ env.VERSION }}
          path: capacitor/android/app/build/outputs/apk/debug/app-debug.apk
